### ISSUE TITLE
Could i use reative method in iron-router?

### ISSUE THREAD

**Issue by thearabbit** [stubailo/meteor-reactive-method#5] opened 2015-04-07 10:06 UTC
I have like this

``` javascript
   // In router
    this.render('myTemplate', {
        data: function () {
            return ReactiveMethod.call("myMethod", "a", "b");;
    });
```

**Comment by stubailo** [comment] 2015-04-08 09:08
I think it should work - have you tried it?

**Comment by thearabbit** [comment] 2015-04-09 00:34
Not work for me.

**Comment by stubailo** [comment] 2015-04-10 06:07
Interesting - could you give me an app where you have this implemented that I could take a look at?

**Comment by stubailo** [comment] 2015-04-23 00:04
Closing due to lack of reproduction.

**Closed as completed by stubailo** 2015-04-23 00:04 UTC

**Comment by rabbittc** [comment] 2015-04-23 02:34
Sorry, I am late.

**Comment by stubailo** [comment] 2015-04-23 03:21
Do you have a reproduction of it not working with iron router?

**Comment by rabbittc** [comment] 2015-04-24 06:43
Now it work fine.
Thanks again :100:
